"""add document storage fields

Revision ID: 71b59d202d35
Revises: 8bee6f36e2a9
Create Date: 2026-09-18 14:34:40.780869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b59d202d35'
down_revision: Union[str, Sequence[str], None] = '8bee6f36e2a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_path', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'storage_path')
    # ### end Alembic commands ###
