"""add document processing tracking

Revision ID: d74169425fb9
Revises: 71b59d202d35
Create Date: 2026-09-21 10:12:56.951901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74169425fb9'
down_revision: Union[str, Sequence[str], None] = '71b59d202d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('processing_started_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('attempt_count', sa.Integer(), nullable=False,server_default="0"))
    op.add_column('documents', sa.Column('last_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'last_error')
    op.drop_column('documents', 'attempt_count')
    op.drop_column('documents', 'processing_started_at')
    # ### end Alembic commands ###
